// AUTO-GENERATED from experiment/inputs/*.md — dev-mode corpus (question+transcript).
// profile = expected PHASE 1 [S,T,R] from a prior run; shown as a hint only (PHASE 1 runs live).

export const CORPUS = [
  {"id": "p1_q1", "questionId": "q1", "profile": [2, 2, 1], "transcript": "Um, so last semester I had a team project in my, uh, materials class, and we had to design like a small experiment together. And there was one guy who really wanted to, um, focus everything on one method, but I thought we should test two conditions, you know, to compare. So it was kind of, um, tense at first. What I did was I just made a small table, like showing what each method would cost us in time, and I shared it in our group chat so everyone could see. And then we talked about it in the next meeting and, yeah, we kind of decided together. It was okay in the end I think."},
  {"id": "p1_q2'", "questionId": "q2", "profile": [2, 1, 2], "transcript": "So, um, in my lab we had this problem where everyone did the sample prep a little differently, and, uh, the results weren't consistent across people — it was a real reproducibility issue. And, um, yeah, we ended up standardizing the protocol, and after that the variance between people dropped a lot, like our results got way more consistent. It was a solid improvement for the lab."},
  {"id": "p1_q2", "questionId": "q2", "profile": [2, 2, 2], "transcript": "Okay so, in my lab there was this, um, equipment log that nobody was really updating, like people would use the machine and not write it down. And I felt like it was a problem because we couldn't track anything. So I, um, I made a new sheet, like a shared one online, and I put reminders next to the machine, like physical notes. And I also asked the lab manager if I could mention it in the group meeting. So after that, um, more people started writing it down. I think like most people used it after a while, yeah."},
  {"id": "p1_q3", "questionId": "q3", "profile": [2, 2, 1], "transcript": "Um, there was a week where I had like, uh, a midterm and also a lab report due and also I was helping with a, um, an event for our department. So it was a lot at the same time. What I did was, um, I kind of made a list every morning of what's most urgent, and I tried to do the lab report first because it was, uh, worth more. And for the event I just did the parts I promised and, um, told the others I couldn't do more. Yeah so I just, I managed I guess. It was stressful but."},
  {"id": "p2_q1'", "questionId": "q1", "profile": [2, 1, 2], "transcript": "Ah, um, so last semester in my team project, we were, uh, making a survey study, and there was a big disagreement about, um, whether to run it online or in person. Like half the team wanted in person for, uh, better quality data, and the other half said online is faster and cheaper. It was kind of a stressful back-and-forth for a while, honestly. And, um... yeah, it sort of resolved itself eventually and we went with a mix. In the end we got over 200 responses, which was way more than we needed for the analysis."},
  {"id": "p2_q1", "questionId": "q1", "profile": [2, 1, 1], "transcript": "Ah, okay, um... so, this is in my, uh, high school actually, no wait, um, in my first year here, there was a, like a group in the, um, student council thing. And, uh, we were planning a, a festival, like a small one. And, um, some people they wanted to make it very big, like invite many, uh, outside people, and some wanted small. I was, um... I was kind of in the middle? I didn't really, um, I mean I said my opinion but I'm not, uh, I'm not good at like arguing. So, um... yeah, they, they discussed a lot and, uh, in the end we did something in between I think. I don't really remember exactly what happened, honestly."},
  {"id": "p2_q2", "questionId": "q2", "profile": [2, 2, 1], "transcript": "Um, initiative... okay. So, uh, in my dorm, the, um, the recycling was very messy, like people just throw everything in one place. And it was, um, bothering me. So I, um, I made some signs, like which bin is for what, and I put them, uh, on the wall. And, um, I also I talked to a few people on my floor about it. Uh... but I don't know if it, if it really changed a lot? Some people maybe followed it. It's hard to say, um, honestly I'm not sure it worked that well."},
  {"id": "p2_q3", "questionId": "q3", "profile": [2, 1, 1], "transcript": "Oh, um, parallel tasks... yeah that happens a lot to me honestly. Like, um, one time I had, uh, two assignments and also my part-time, like a cafe job, on the same, uh, same week. And it was, it was really, um, a lot. I was very tired. Uh... what did I do... I think I just, um, I just tried to do everything but I was, uh, kind of late on one of them. Like I asked the professor for, um, one more day. So, uh, yeah. It was, it was hard. I don't really have a, um, a good system for that, I just kind of survive, haha."},
  {"id": "p3_q1", "questionId": "q1", "profile": [2, 2, 2], "transcript": "Yeah, so this was during a, um, a hackathon last year. My team was building like a small app, and me and another member, we really disagreed on the, uh, the tech stack. He wanted to use something he already knew, but I thought it wouldn't scale for what we wanted. So instead of just arguing, um, I suggested we each build a quick prototype of the core feature in like two hours, and then just compare. So we did that, and honestly his version had a bug that would've taken forever to fix, and mine was, um, running smoothly. So we went with mine, and we actually, uh, we ended up placing second in the hackathon, so it worked out. And he was cool about it in the end."},
  {"id": "p3_q2'", "questionId": "q2", "profile": [1, 2, 2], "transcript": "Yeah, so, um, I set up this whole automated backup system for our lab. Like I wrote a script that runs every night and syncs everything to the cloud, and I added a Slack alert that pings us if it ever fails. I tested it for a couple weeks, fixed a few edge cases, and, um, now it's been running for like four months straight without a hitch. We haven't lost a single file since. Honestly it just felt like something that needed doing."},
  {"id": "p3_q2", "questionId": "q2", "profile": [2, 2, 2], "transcript": "Okay, initiative. Um, so in one of my classes, the, uh, the group projects always had this problem where nobody knew who's doing what, and it was chaos near the deadline. So I, um, I basically volunteered to set up like a shared task board, um, on Notion, for our team, with deadlines and, uh, assignments. And I kind of, um, kept it updated and reminded people. And, uh, I think it helped, like we finished earlier than other teams, um, at least it felt less stressful. The professor didn't really comment on it but, yeah, internally it was smoother."},
  {"id": "p3_q3", "questionId": "q3", "profile": [2, 2, 1], "transcript": "Um, so this semester honestly has been, uh, a lot of parallel stuff. Like I'm doing a research project with a professor, and I'm also, um, TAing for a course, and taking three classes. So, um, the way I handle it, I, uh, I time-block my week, like I give the research fixed slots so it doesn't get, um, pushed by the urgent class stuff. And for the TA work I batch it, like I do all the grading in one sitting instead of, um, spreading it. So, yeah, I try to be systematic about it. Um... it's going, I guess? Like I'm keeping up so far, nothing has, um, blown up yet."},
  {"id": "p4_q1'", "questionId": "q1", "profile": [1, 0, 2], "transcript": "Um, yeah, there was some disagreement in a group project, and, uh, we worked it out. In the end it turned out really well — we actually got the top grade in the class."},
  {"id": "p4_q1", "questionId": "q1", "profile": [2, 2, 1], "transcript": "Um, yeah, so in a class project we had, like, four people, and two of us wanted to do the topic on, uh, renewable energy and the other two wanted something about AI. So there was some disagreement. Um, I kind of pushed for the energy one, like I sent some example papers to show it's, uh, more doable. And, um, we did like a quick vote after. Yeah. That's, that's basically what happened."},
  {"id": "p4_q2", "questionId": "q2", "profile": [1, 0, 2], "transcript": "Okay, um, initiative. So, in our department there was, uh, no proper place for students to find like past exam papers, everyone just, um, asked seniors randomly. And, uh, now there's actually a shared drive with all the past exams organized by course, and people use it a lot, it's really helpful. Um... yeah. So that got, uh, that got sorted out."},
  {"id": "p4_q3'", "questionId": "q3", "profile": [1, 2, 2], "transcript": "Um, it was a busy week, so I just, uh, made a schedule and stuck to it. I put the hardest things in the mornings and the smaller stuff at night, and I turned off my phone notifications while I worked. Yeah. I got everything in on time, nothing was late."},
  {"id": "p4_q3", "questionId": "q3", "profile": [2, 0, 0], "transcript": "Um, parallel... yeah. So near the end of last semester I had like three big things due in the same week, a project, a presentation, and a take-home exam. And on top of that my, um, my part-time shifts didn't change so I was working too. It was honestly one of the most stressful weeks, I barely slept. Um... yeah, it was just a really heavy week."},
];
